//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.24 at 10:24:02 PM CEST 
//


package com.eclipsesource.icat.schemaxml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.eclipse.persistence.oxm.annotations.XmlCDATA;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Bk" minOccurs="0"/>
 *         &lt;element ref="{}CascadeType" minOccurs="0"/>
 *         &lt;element ref="{}Column" minOccurs="0"/>
 *         &lt;element ref="{}CustomType" minOccurs="0"/>
 *         &lt;element ref="{}DbType" minOccurs="0"/>
 *         &lt;element ref="{}Digit" minOccurs="0"/>
 *         &lt;element ref="{}Fk" minOccurs="0"/>
 *         &lt;element ref="{}Insertable"/>
 *         &lt;element ref="{}JavaType"/>
 *         &lt;element ref="{}JoinDstKey" minOccurs="0"/>
 *         &lt;element ref="{}JoinSrcKey" minOccurs="0"/>
 *         &lt;element ref="{}JoinTable" minOccurs="0"/>
 *         &lt;element ref="{}Length"/>
 *         &lt;element ref="{}Lob" minOccurs="0"/>
 *         &lt;element ref="{}MappedBy" minOccurs="0"/>
 *         &lt;element ref="{}Name"/>
 *         &lt;element ref="{}Nullable"/>
 *         &lt;element ref="{}Pk"/>
 *         &lt;element ref="{}Relation" minOccurs="0"/>
 *         &lt;element ref="{}Updatable"/>
 *         &lt;element ref="{}XmlAttribute" minOccurs="0"/>
 *         &lt;element ref="{}XmlName" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bk",
    "cascadeType",
    "column",
    "customType",
    "dbType",
    "digit",
    "fk",
    "insertable",
    "javaType",
    "joinDstKey",
    "joinSrcKey",
    "joinTable",
    "length",
    "lob",
    "mappedBy",
    "name",
    "nullable",
    "pk",
    "relation",
    "updatable",
    "xmlAttribute",
    "xmlName"
})
@XmlRootElement(name = "Field")
public class Field {

    @XmlElement(name = "Bk", defaultValue = "false")
    protected Boolean bk;
    @XmlElement(name = "CascadeType")
    @XmlCDATA
    protected String cascadeType;
    @XmlElement(name = "Column")
    @XmlCDATA
    protected String column;
    @XmlElement(name = "CustomType")
    @XmlCDATA
    protected String customType;
    @XmlElement(name = "DbType")
    protected Short dbType;
    @XmlElement(name = "Digit")
    protected Short digit;
    @XmlElement(name = "Fk", defaultValue = "false")
    protected Boolean fk;
    @XmlElement(name = "Insertable", defaultValue = "false")
    protected boolean insertable;
    @XmlElement(name = "JavaType", required = true)
    @XmlCDATA
    protected String javaType;
    @XmlElement(name = "JoinDstKey")
    @XmlCDATA
    protected String joinDstKey;
    @XmlElement(name = "JoinSrcKey")
    @XmlCDATA
    protected String joinSrcKey;
    @XmlElement(name = "JoinTable")
    @XmlCDATA
    protected String joinTable;
    @XmlElement(name = "Length", defaultValue = "0")
    protected short length;
    @XmlElement(name = "Lob", defaultValue = "false")
    protected Boolean lob;
    @XmlElement(name = "MappedBy")
    @XmlCDATA
    protected String mappedBy;
    @XmlElement(name = "Name", required = true)
    @XmlCDATA
    protected String name;
    @XmlElement(name = "Nullable", defaultValue = "false")
    protected boolean nullable;
    @XmlElement(name = "Pk", defaultValue = "false")
    protected boolean pk;
    @XmlElement(name = "Relation", defaultValue = "false")
    @XmlCDATA
    protected String relation;
    @XmlElement(name = "Updatable", defaultValue = "false")
    protected boolean updatable;
    @XmlElement(name = "XmlAttribute", defaultValue = "false")
    protected Boolean xmlAttribute;
    @XmlElement(name = "XmlName")
    @XmlCDATA
    protected String xmlName;

    /**
     * Gets the value of the bk property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBk() {
        return bk;
    }

    /**
     * Sets the value of the bk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBk(Boolean value) {
        this.bk = value;
    }

    /**
     * Gets the value of the cascadeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCascadeType() {
        return cascadeType;
    }

    /**
     * Sets the value of the cascadeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCascadeType(String value) {
        this.cascadeType = value;
    }

    /**
     * Gets the value of the column property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumn() {
        return column;
    }

    /**
     * Sets the value of the column property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumn(String value) {
        this.column = value;
    }

    /**
     * Gets the value of the customType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomType() {
        return customType;
    }

    /**
     * Sets the value of the customType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomType(String value) {
        this.customType = value;
    }

    /**
     * Gets the value of the dbType property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getDbType() {
        return dbType;
    }

    /**
     * Sets the value of the dbType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setDbType(Short value) {
        this.dbType = value;
    }

    /**
     * Gets the value of the digit property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getDigit() {
        return digit;
    }

    /**
     * Sets the value of the digit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setDigit(Short value) {
        this.digit = value;
    }

    /**
     * Gets the value of the fk property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFk() {
        return fk;
    }

    /**
     * Sets the value of the fk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFk(Boolean value) {
        this.fk = value;
    }

    /**
     * Gets the value of the insertable property.
     * 
     */
    public boolean isInsertable() {
        return insertable;
    }

    /**
     * Sets the value of the insertable property.
     * 
     */
    public void setInsertable(boolean value) {
        this.insertable = value;
    }

    /**
     * Gets the value of the javaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaType() {
        return javaType;
    }

    /**
     * Sets the value of the javaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaType(String value) {
        this.javaType = value;
    }

    /**
     * Gets the value of the joinDstKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoinDstKey() {
        return joinDstKey;
    }

    /**
     * Sets the value of the joinDstKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoinDstKey(String value) {
        this.joinDstKey = value;
    }

    /**
     * Gets the value of the joinSrcKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoinSrcKey() {
        return joinSrcKey;
    }

    /**
     * Sets the value of the joinSrcKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoinSrcKey(String value) {
        this.joinSrcKey = value;
    }

    /**
     * Gets the value of the joinTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoinTable() {
        return joinTable;
    }

    /**
     * Sets the value of the joinTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoinTable(String value) {
        this.joinTable = value;
    }

    /**
     * Gets the value of the length property.
     * 
     */
    public short getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     */
    public void setLength(short value) {
        this.length = value;
    }

    /**
     * Gets the value of the lob property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLob() {
        return lob;
    }

    /**
     * Sets the value of the lob property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLob(Boolean value) {
        this.lob = value;
    }

    /**
     * Gets the value of the mappedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMappedBy() {
        return mappedBy;
    }

    /**
     * Sets the value of the mappedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMappedBy(String value) {
        this.mappedBy = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nullable property.
     * 
     */
    public boolean isNullable() {
        return nullable;
    }

    /**
     * Sets the value of the nullable property.
     * 
     */
    public void setNullable(boolean value) {
        this.nullable = value;
    }

    /**
     * Gets the value of the pk property.
     * 
     */
    public boolean isPk() {
        return pk;
    }

    /**
     * Sets the value of the pk property.
     * 
     */
    public void setPk(boolean value) {
        this.pk = value;
    }

    /**
     * Gets the value of the relation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelation() {
        return relation;
    }

    /**
     * Sets the value of the relation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelation(String value) {
        this.relation = value;
    }

    /**
     * Gets the value of the updatable property.
     * 
     */
    public boolean isUpdatable() {
        return updatable;
    }

    /**
     * Sets the value of the updatable property.
     * 
     */
    public void setUpdatable(boolean value) {
        this.updatable = value;
    }

    /**
     * Gets the value of the xmlAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXmlAttribute() {
        return xmlAttribute;
    }

    /**
     * Sets the value of the xmlAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXmlAttribute(Boolean value) {
        this.xmlAttribute = value;
    }

    /**
     * Gets the value of the xmlName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlName() {
        return xmlName;
    }

    /**
     * Sets the value of the xmlName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlName(String value) {
        this.xmlName = value;
    }

}
