//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.24 at 10:24:02 PM CEST 
//


package com.eclipsesource.icat.importxml.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.eclipsesource.icat.importxml.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _JoinSrcKey_QNAME = new QName("", "JoinSrcKey");
    private final static QName _XmlAttribute_QNAME = new QName("", "XmlAttribute");
    private final static QName _PackageName_QNAME = new QName("", "PackageName");
    private final static QName _Parent_QNAME = new QName("", "Parent");
    private final static QName _JoinDstKey_QNAME = new QName("", "JoinDstKey");
    private final static QName _Schema_QNAME = new QName("", "Schema");
    private final static QName _Unit_QNAME = new QName("", "Unit");
    private final static QName _Name_QNAME = new QName("", "Name");
    private final static QName _Relation_QNAME = new QName("", "Relation");
    private final static QName _Column_QNAME = new QName("", "Column");
    private final static QName _Updatable_QNAME = new QName("", "Updatable");
    private final static QName _XmlName_QNAME = new QName("", "XmlName");
    private final static QName _Pk_QNAME = new QName("", "Pk");
    private final static QName _Deleted_QNAME = new QName("", "Deleted");
    private final static QName _Insertable_QNAME = new QName("", "Insertable");
    private final static QName _Lob_QNAME = new QName("", "Lob");
    private final static QName _CustomType_QNAME = new QName("", "CustomType");
    private final static QName _Digit_QNAME = new QName("", "Digit");
    private final static QName _Table_QNAME = new QName("", "Table");
    private final static QName _Fk_QNAME = new QName("", "Fk");
    private final static QName _MappedBy_QNAME = new QName("", "MappedBy");
    private final static QName _Bk_QNAME = new QName("", "Bk");
    private final static QName _DbType_QNAME = new QName("", "DbType");
    private final static QName _JavaType_QNAME = new QName("", "JavaType");
    private final static QName _Length_QNAME = new QName("", "Length");
    private final static QName _CascadeType_QNAME = new QName("", "CascadeType");
    private final static QName _Application_QNAME = new QName("", "Application");
    private final static QName _Nullable_QNAME = new QName("", "Nullable");
    private final static QName _JoinTable_QNAME = new QName("", "JoinTable");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.eclipsesource.icat.importxml.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "JoinSrcKey")
    public JAXBElement<String> createJoinSrcKey(String value) {
        return new JAXBElement<String>(_JoinSrcKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "XmlAttribute", defaultValue = "false")
    public JAXBElement<Boolean> createXmlAttribute(Boolean value) {
        return new JAXBElement<Boolean>(_XmlAttribute_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PackageName")
    public JAXBElement<String> createPackageName(String value) {
        return new JAXBElement<String>(_PackageName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Parent")
    public JAXBElement<String> createParent(String value) {
        return new JAXBElement<String>(_Parent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "JoinDstKey")
    public JAXBElement<String> createJoinDstKey(String value) {
        return new JAXBElement<String>(_JoinDstKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Schema")
    public JAXBElement<String> createSchema(String value) {
        return new JAXBElement<String>(_Schema_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Unit")
    public JAXBElement<String> createUnit(String value) {
        return new JAXBElement<String>(_Unit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Relation", defaultValue = "false")
    public JAXBElement<String> createRelation(String value) {
        return new JAXBElement<String>(_Relation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Column")
    public JAXBElement<String> createColumn(String value) {
        return new JAXBElement<String>(_Column_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Updatable", defaultValue = "false")
    public JAXBElement<Boolean> createUpdatable(Boolean value) {
        return new JAXBElement<Boolean>(_Updatable_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "XmlName")
    public JAXBElement<String> createXmlName(String value) {
        return new JAXBElement<String>(_XmlName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Pk", defaultValue = "false")
    public JAXBElement<Boolean> createPk(Boolean value) {
        return new JAXBElement<Boolean>(_Pk_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Deleted", defaultValue = "false")
    public JAXBElement<Boolean> createDeleted(Boolean value) {
        return new JAXBElement<Boolean>(_Deleted_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Insertable", defaultValue = "false")
    public JAXBElement<Boolean> createInsertable(Boolean value) {
        return new JAXBElement<Boolean>(_Insertable_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Lob", defaultValue = "false")
    public JAXBElement<Boolean> createLob(Boolean value) {
        return new JAXBElement<Boolean>(_Lob_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CustomType")
    public JAXBElement<String> createCustomType(String value) {
        return new JAXBElement<String>(_CustomType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Digit")
    public JAXBElement<Short> createDigit(Short value) {
        return new JAXBElement<Short>(_Digit_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Table")
    public JAXBElement<String> createTable(String value) {
        return new JAXBElement<String>(_Table_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Fk", defaultValue = "false")
    public JAXBElement<Boolean> createFk(Boolean value) {
        return new JAXBElement<Boolean>(_Fk_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MappedBy")
    public JAXBElement<String> createMappedBy(String value) {
        return new JAXBElement<String>(_MappedBy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Bk", defaultValue = "false")
    public JAXBElement<Boolean> createBk(Boolean value) {
        return new JAXBElement<Boolean>(_Bk_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DbType")
    public JAXBElement<Short> createDbType(Short value) {
        return new JAXBElement<Short>(_DbType_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "JavaType")
    public JAXBElement<String> createJavaType(String value) {
        return new JAXBElement<String>(_JavaType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Length", defaultValue = "0")
    public JAXBElement<Short> createLength(Short value) {
        return new JAXBElement<Short>(_Length_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CascadeType")
    public JAXBElement<String> createCascadeType(String value) {
        return new JAXBElement<String>(_CascadeType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Application")
    public JAXBElement<String> createApplication(String value) {
        return new JAXBElement<String>(_Application_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Nullable", defaultValue = "false")
    public JAXBElement<Boolean> createNullable(Boolean value) {
        return new JAXBElement<Boolean>(_Nullable_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "JoinTable")
    public JAXBElement<String> createJoinTable(String value) {
        return new JAXBElement<String>(_JoinTable_QNAME, String.class, null, value);
    }

}
